engines:
  rubocop:
    enabled: true
    config: .codeclimate_rubocop.yml
  golint:
    enabled: false
  gofmt:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
   paths:
   - lib/**
   - mod/**
   - "**.rb"
exclude_paths:
- vendor/**/*
- mod/*/{data/files,public,vendor}/**/*
- mod/**/lib/javascript/**/*.js
- mod/**/*.min.css
- test/**/*
- db/**/*
- script/single-use/**/*
- mod/deckorate_research/assets/script/jpages.js
