AllCops:
  TargetRubyVersion: 2.5
#  Include:
#  - "**/*.gemspec"
#  - "**/*.podspec"
#  - "**/*.jbuilder"
#  - "**/*.rake"
#  - "**/*.opal"
#  - "**/Gemfile"
#  - "**/Rakefile"
#  - "**/Capfile"
#  - "**/Guardfile"
#  - "**/Podfile"
#  - "**/Thorfile"
#  - "**/Vagrantfile"
#  - "**/Berksfile"
#  - "**/Cheffile"
#  - "**/Vagabondfile"
  Exclude:
  - "vendor/**/*"
  - "db/schema.rb"
  - "mod/wikirate_source/files/**/*"
  - "mod/wikirate_source/lib/javascript/**/*"
  DisplayCopNames: false
  StyleGuideCopsOnly: false
Style/CommentAnnotation:
  Enabled: true
Style/CollectionMethods:
  Description: Preferred collection methods.
  Enabled: true
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    detect: 'find'
    find_all: 'select'
    reduce: 'inject'
Layout/DotPosition:
  EnforcedStyle: leading
Style/Encoding:
  Description: Use UTF-8 as the source file encoding.
  Enabled: false
Style/GuardClause:
  Description: Check for conditionals that can be replaced with guard clauses
  Enabled: true
Style/MethodDefParentheses:
  Description: Checks if the method definitions have or don't have 252
  Enabled: true
  EnforcedStyle: require_no_parentheses
Style/RegexpLiteral:
  Description: Use %r for regular expressions matching more than
               `MaxSlashes` '/' characters. Use %r only for regular expressions
               matching more than `MaxSlashes` '/' character.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#percent-r
  Enabled: true
Style/StringLiterals:
  EnforcedStyle: double_quotes
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 15
Layout/ExtraSpacing:
  Description: Do not use unnecessary spacing.
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: true
  AllowSafeAssignment: true
Lint/AmbiguousRegexpLiteral:
  Exclude:
    - '**/*_spec.rb'
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*_spec.rb'
RSpec/ExampleLength:
  Description: Checks for long examples.
  Enabled: false
  Max: 15
RSpec/FilePath:
  Description: Checks that spec file paths are consistent with the test subject.
  Enabled: true
  CustomTransform:
    RuboCop: rubocop
    RSpec: rspec
    Card: spec
  IgnoreMethods: false
RSpec/NestedGroups:
  Description: Checks for nested example groups.
  Enabled: false
  Max: 5
RSpec/InstanceVariable:
  Enabled: false
Metrics/LineLength:
  Enabled: true
  Max: 90
RSpec/MultipleExpectations:
  Enabled: false
Style/Documentation:
  Exclude:
    - db/migrate_cards/*.rb
Style/SymbolArray:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'
Style/Alias:
  Enabled: false
  AutoCorrect: false
