# -*- encoding : utf-8 -*-

class SpecialPointer < Card::Migration
  def up
    Card.create! :name=>"production_export",:type_id=>Card::PointerID,:content=>%{
      [[card with codename]]
[[all card type]]
[[*all+*style]]
[[*all+*script]]
[[home]]
[[Source+*type+*autoname]]
[[Apple Inc.]]
[[Amazon.com, Inc.]]
[[Amazon.com, Inc.+aliases]]
[[Samsung]]
[[Siemens AG]]
[[Sony Corporation]]
[[Natural Resource Use]]
[[Community]]
[[Human Rights]]
[[Climate Change]]
[[Animal Welfare]]
[[Sebastian Jekutsch+CSR Report Available]]
[[Good Company Index+Good Company Grade]]
[[BSR+BSR Member]]
[[Access to Nutrition Index+Marketing Score]]
[[Year]]
[[year+*type+by_update]]
[[Metric+company+*type plus right+*structure]]
[[loading gif]]
[[creator credit]]
[[Note+*type+*add help]]
[[citation_count]]
[[note+citation count+*type plus right]]
[[note+citation count+*type plus right+*structure]]
[[topic+*right+*default]]
[[company+*right+*default]]
[[missing image]]
[[Metric value+source+*type plus right+*default]]
[[Source+*type+*structure]]
[[Metric value+*type+*structure]]
[[metric company add value]]
[[metric add value]]
[[Company+*right+*default]]
[[Year+*right+*default]]
[[Metric value+value+*type plus right+*default]]
[[Apple Inc.+Natural Resource Use]]
[[Apple Inc.+Natural Resource Use+overview]]
[[Samsung+Natural Resource Use]]
[[Samsung+Natural Resource Use+overview]]
[[*Vertical Logo]]
[[company+limited metric+*type plus right+*structure]]
[[yinyang drag item]]
[[yinyang drag item+*right+*structure]]
[[source+icon]]
[[metric+icon]]
[[overview+icon]]
[[note+icon]]
[[initiative+icon]]
[[Company+contribution+*type plus right]]
[[Company+contribution+*type plus right+*structure]]
[[contribution+*right]]
[[contribution+*right+*structure]]
[[company+*type+*structure]]
[[topic+*type+*structure]]
[[analysis+*type+*structure]]
    }
  end
end
