#!/usr/bin/env ruby

# SPDX-FileCopyrightText: 2022 WikiRate info@wikirate.org
#
# SPDX-License-Identifier: GPL-3.0-or-later

# This command will be run when you use `card` from within your deck.

APP_PATH = File.expand_path("../config/application", __dir__)
require File.expand_path("../../config/boot",  __FILE__)
require "cardio/commands"
