#!/usr/bin/env ruby
# used to run cucumber in RubyMine

# SPDX-FileCopyrightText: 2022 WikiRate info@wikirate.org
#
# SPDX-License-Identifier: GPL-3.0-or-later

ARGV.insert 0, "cucumber", "--"#, '--no-simplecov', "--" #,'--default-path=/opt/'
APP_PATH = File.expand_path("../../config/application",  __FILE__)
require File.expand_path("../../config/boot",  __FILE__)
require "decko/commands"
