#!/usr/bin/env ruby
# used to run cucumber in RubyMine

ARGV.insert 0, "cucumber", "--"#, '--no-simplecov', "--" #,'--default-path=/opt/wagn'
APP_PATH = File.expand_path("../../config/application",  __FILE__)
require File.expand_path("../../config/boot",  __FILE__)
require "decko/commands"
