#!/usr/bin/env ruby

# SPDX-FileCopyrightText: 2014 2014 Laureen van Breen, <laureen@wikirate.org> et al.
#
# SPDX-License-Identifier: GPL-3.0-or-later

# used to run cucumber in RubyMine

ARGV.insert 0, "cucumber", "--"#, '--no-simplecov', "--" #,'--default-path=/opt/'
APP_PATH = File.expand_path("../../config/application",  __FILE__)
require File.expand_path("../../config/boot",  __FILE__)
require "decko/commands"
