#!/usr/bin/env ruby

# SPDX-FileCopyrightText: 2014 2014 Laureen van Breen, <laureen@wikirate.org> et al.
#
# SPDX-License-Identifier: GPL-3.0-or-later

require File.expand_path("../../config/environment", __FILE__)
require "delayed/command"

Delayed::Command.new(ARGV).daemonize
