#!/usr/bin/env ruby
# used to run rspec in RubyMine

ARGV.insert 0,
            "rspec", "--no-simplecov", "--", "--default-path=/opt/wagn"

APP_PATH = File.expand_path("../../config/application",  __FILE__)
require File.expand_path("../../config/boot",  __FILE__)
require "decko/commands"
