#!/usr/bin/env ruby
# used to run rspec in RubyMine

ARGV = ["rspec", "--no-simplecov", "--", "--default-path=/opt/wagn"] + ARGV
APP_PATH = File.expand_path("../../config/application",  __FILE__)
require File.expand_path("../../config/boot",  __FILE__)
require "wagn/commands"
